version: '2'

services:
  redis:
    image: redis:5.0.4
    command: redis-server

  redcom:
    image: tenstartups/redis-commander
    command: --redis-host redis
    ports:
      - '3381:8081'

  db:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty
      MYSQL_DATABASE: dev_db
      MYSQL_USER: kirill
      MYSQL_PASSWORD: Qwerty
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: './server'
    depends_on:
      - db
      - redis
#    image: kirillche/bmern
    ports:
      - "5000:5000"
    #restart: always
    container_name: back
    volumes:
      - ./server:/app
      - /app/node_modules
#      - notused:/opt/app/node_modules
#    command: sh -c 'tail -f /dev/null'
    command: sh -c 'npm start'

  frontend:
    build: './client'
    depends_on:
      - db
#    image: kirillche/fmern
    ports:
      - "5100:3000"
    #restart: always
    container_name: front
    volumes:
      - ./client:/app
      - /app/node_modules
#      - notused:/opt/app/node_modules
#    command: sh -c 'tail -f /dev/null'
    command: sh -c 'npm start'

  myadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "5151:80"
    #restart: always
    environment:
      - PMA_HOST=db

  haproxy:
    image: haproxy:1.9.6
    container_name: haproxy
    volumes:
      - /dev/log:/dev/log
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - backend
      - frontend
    ports:
      - "3100:80"

volumes:
  db_data:
#  notused:
