export { default as Main } from './Main.component';
export { default as ImageGrid } from './ImageGrid.component';
export { default as Search } from './Search.component';
export { default as Filter } from './Filter.component';
export { default as Login } from './Login.component';
export { default as ForgotPwd } from './ForgotPwd.component';
export { default as ProfileMenu } from './ProfileMenu.component';
export { default as SignUp } from './SignUp.component';
export { default as SignUpGuru } from './SignUpGuru.component';
export { default as SignUpAdept } from './SignUpAdept.component';
export { default as Profile } from './Profile.component';
export { default as EditProfile } from './EditProfile.component';
export { default as SetNewPwd } from './SetNewPwd.component';
export { default as MessagesList } from './MessagesList.component';
export { default as Chat } from './Chat.component';
// export { default as ImageDropzone } from './imageDropzone.component';
